version: "3"
services:
  redis:
    image: redis
    restart: always
  db:
    image: mariadb:10
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_AUTO_UPGRADE: "true"
    volumes:
      - "${SRV_DIR}/mariadb:/var/lib/mysql"
  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "${SRV_DIR}/mysql:/var/lib/mysql"
    cap_add:
      - SYS_NICE
  world1:
    restart: unless-stopped
    build:
      context: ./server
      args:
        SERVER_URL:
        EULA:
        PID:
        PGID:
    volumes:
      - "${SRV_DIR}/world1:/srv"
    cap_drop:
      - ALL
    stdin_open: true
    init: true
    depends_on:
      - db
      - mysql-db
      - redis
  proxy:
    restart: always
    build:
      context: ./proxy
      args:
        PROXY_URL:
        PID:
        PGID:
    ports:
      - "25565:25577"
    volumes:
      - "${SRV_DIR}/proxy:/srv"
    cap_drop:
      - ALL
    stdin_open: true
    init: true
    depends_on:
      - world1
  watcher:
    image: minecraft-watcher
    restart: "unless-stopped"
    build:
      context: ./minecraft-watcher
    environment:
      KILL_WEBHOOK: ${KILL_WEBHOOK}
      HOST: ${HOST}
      LOG_LEVEL: ${LOG_LEVEL}
      TIMEOUT_S: ${TIMEOUT_S}
      PORT: ${PORT}
    cap_drop:
      - ALL
    init: true
    depends_on:
      - proxy
