version: "3"
services:
  server:
    restart: unless-stopped
    build:
      context: .
      args:
        PID: 976
        PGID: 976
    ports:
      - "25565:25565"
    volumes:
      - "/minecraft-srv:/srv/minecraft/world"
    cap_drop:
      - ALL
    stdin_open: true
